name: Deploy NodeJS App

on:
  push:

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Onboardbase
        run: |-
          yarn global add @onboardbase/cli
          onboardbase --version
      - name: Setup Onboardbase
        run: |-
          onboardbase secrets --env > .env
          cat .env
        env:
            ONBOARDBASE_PROJECT: new
            ONBOARDBASE_ENVIRONMENT: development
            ONBOARDBASE_TOKEN: ${{ secrets.ONBOARDBASE_TOKEN }}

